[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.ts"
  [headers.values]
    Content-Type = "application/javascript"
